---
server:
 port: 8099

logging:
 level:
    com.sap.cds.security.authentication: DEBUG

cds:
 security:
    mock.users:
     - name: MasterDataAdmin
       password: admin
    openUnrestrictedEndpoints: true
    openMetadataEndpoints: true 
    xsuaa.enabled: false
    defaultRestrictionLevel: any

spring:
  web.resources.static-locations: "file:./app/webapp"
  config.activate.on-profile: default
  datasource:
    url: "jdbc:sqlite:/home/user/projects/BPEventHandler/sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never # original value always ...if you keep always on starting your entries would be deleted
    hikari:
      maximum-pool-size: 1
